export default Data = [
    {
        name: "Harshit Upadhyaya",
        location: "Jaipur",
        occupation: "Student",
        distance: "within 2.0 KM",
        title: "Coffee | Business | Friendship",
        description: "Energetic and passionate college student pursuing BCA at Poornima University, Jaipur. Aim to grow with the company where I can effectively contribute my skills as a professional and utilize my knowledge for mutual growth.",
        section: "Personal",
    },
    {
        name: "Khushi Mittal",
        location: "Bulandshahr",
        occupation: "Software Engineer",
        distance: "within 18.1 KM",
        title: "Coffee | Business",
        description: "College student studying B.Com from SOL DU and also pursuing CA as another course.",
        section: "Business",
    },
    {
        name: "Mohit Singh",
        location: "Noida",
        occupation: "UI UX Designer",
        distance: "within 19.5 KM",
        title: "Coffee | Friendship",
        description: "",
        section: "Merchant",
    },
    {
        name: "Amit Patel",
        location: "Mumbai",
        occupation: "Marketing Executive",
        distance: "within 5.3 KM",
        title: "Coffee | Business",
        description: "Experienced marketing professional with a focus on driving business growth through strategic campaigns.",
        section: "Business",
    },
    {
        name: "Neha Sharma",
        location: "Delhi",
        occupation: "Graphic Designer",
        distance: "within 12.7 KM",
        title: "Coffee | Friendship",
        description: "Passionate about creating visually stunning designs that communicate effectively.",
        section: "Personal",
    },
    {
        name: "Raj Gupta",
        location: "Bangalore",
        occupation: "Entrepreneur",
        distance: "within 8.2 KM",
        title: "Coffee | Business | Friendship",
        description: "Founder of a tech startup aiming to revolutionize the way people connect and collaborate.",
        section: "Business",
    },
    {
        name: "Anjali Verma",
        location: "Chennai",
        occupation: "Financial Analyst",
        distance: "within 15.4 KM",
        title: "Coffee | Business",
        description: "Analytical thinker with a strong background in financial modeling and risk analysis.",
        section: "Business",
    },
    {
        name: "Vikram Singh",
        location: "Hyderabad",
        occupation: "Teacher",
        distance: "within 10.8 KM",
        title: "Coffee | Friendship",
        description: "Dedicated educator with a passion for inspiring students to reach their full potential.",
        section: "Personal",
    },
    {
        name: "Priya Gupta",
        location: "Kolkata",
        occupation: "Event Planner",
        distance: "within 7.6 KM",
        title: "Coffee | Business",
        description: "Creative event planner with a flair for organizing memorable and seamless events.",
        section: "Business",
    },
    {
        name: "Rahul Kapoor",
        location: "Pune",
        occupation: "Software Developer",
        distance: "within 14.3 KM",
        title: "Coffee | Friendship",
        description: "Passionate coder always looking for innovative solutions to complex problems.",
        section: "Merchant",
    },
    // Additional random entries
    {
        name: "Ananya Singh",
        location: "Lucknow",
        occupation: "Architect",
        distance: "within 9.5 KM",
        title: "Coffee | Business",
        description: "Architect with a keen eye for detail and a passion for creating functional and aesthetically pleasing spaces.",
        section: "Business",
    },
    {
        name: "Rohan Sharma",
        location: "Chandigarh",
        occupation: "Doctor",
        distance: "within 20.2 KM",
        title: "Coffee | Friendship",
        description: "Dedicated medical professional committed to providing quality healthcare and building lasting relationships with patients.",
        section: "Personal",
    },
    {
        name: "Simran Verma",
        location: "Ahmedabad",
        occupation: "HR Manager",
        distance: "within 11.8 KM",
        title: "Coffee | Business",
        description: "Human Resources Manager with expertise in talent acquisition, employee relations, and organizational development.",
        section: "Business",
    },
    {
        name: "Aryan Kapoor",
        location: "Goa",
        occupation: "Chef",
        distance: "within 16.7 KM",
        title: "Coffee | Friendship",
        description: "Passionate chef with a flair for creating innovative and delicious culinary delights.",
        section: "Merchant",
    },
    {
        name: "Sanya Mittal",
        location: "Indore",
        occupation: "Financial Advisor",
        distance: "within 13.4 KM",
        title: "Coffee | Business",
        description: "Experienced financial advisor helping individuals and businesses achieve their financial goals through strategic planning.",
        section: "Business",
    }
];